# Default values for mlflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jianshen92/mlflow # Image Repository
  pullPolicy: Always
  tag: 1.13.1 # Image version is sync to MLFlow Version

backendStore:
  # filepath: 
  postgres:
    username: mlflow # Database Username
    host: # Database Host
    port: # Database Port
    database: mlflow # Database Name
    secretName: postgres-credentials # k8 secret name that contains PG password

defaultArtifactRoot: # S3 bucket

# set true to expose prometheus
metrics:
  enabled: false
  metricsStoreDir: prometheus/metrics # Local directory that stores Prom metrics
  serviceMonitor:
    enabled: false # Enable ServiceMonitor Resource
    labels: []
      # release: kube-prometheus-stack

imagePullSecrets: []
nameOverride: mlflow
fullnameOverride: mlflow

# Service account with permission to access s3 bucket
serviceAccount:
  create: false
  annotations: {}
  name: "" 

service:
  type: ClusterIP
  port: 80

# Ingress settings
ingress:
  enabled: false
  annotations: {} # Depends on your ingress controller
    # kubernetes.io/ingress.class: "nginx-internal"
    # cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: mlflow.your-domain.com
      paths:
        - /
  tls: []
    # - secretName: mlflow-tls
    #   hosts:
    #     - mlflow.your-domain.com

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 0.5Gi
  # requests:
  #   cpu: 500m
  #   memory: 0.5Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
